"use client"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"
import { ArrowRight, Sparkles, MessageSquareCode, ShieldAlert, TrendingUp, Compass, Cpu, Target, FileSpreadsheet, Award } from "lucide-react"
import Link from "next/link"
import { ThemeToggle } from "@/components/theme-toggle"

export default function LandingPage() {
  const innovativeFeatures = [
    {
      icon: TrendingUp,
      title: "🔮 Karma.ai Sentiment Oracle",
      description: "Aggregates simulated real-time r/developersIndia & Twitter crowd sentiment to gauge current hiring temperatures and delay alerts.",
      glow: "border-purple-500/30 hover:border-purple-500/60 dark:hover:shadow-[0_0_20px_rgba(168,85,247,0.15)]",
    },
    {
      icon: Compass,
      title: "🚀 The Tier-Breakout Engine",
      description: "Bypasses standard on-campus college limits with guerilla strategies, cold LinkedIn drafters, and open-source milestones for Tier-2/3 developers.",
      glow: "border-blue-500/30 hover:border-blue-500/60 dark:hover:shadow-[0_0_20px_rgba(59,130,246,0.15)]",
    },
    {
      icon: Cpu,
      title: "💼 WITCH-to-Product Portal",
      description: "Step-by-step transition roadmap for service engineers (TCS/Wipro/Infosys) targeting high-tier software product companies and startups.",
      glow: "border-emerald-500/30 hover:border-emerald-500/60 dark:hover:shadow-[0_0_20px_rgba(16,185,129,0.15)]",
    },
    {
      icon: MessageSquareCode,
      title: "🎙️ ShadowInterview.sh Canvas",
      description: "Immersive audio-inspired mock interview simulator with company-specific parameters, visual feedback curves, and instant Groq critiques.",
      glow: "border-pink-500/30 hover:border-pink-500/60 dark:hover:shadow-[0_0_20px_rgba(236,72,153,0.15)]",
    },
    {
      icon: Target,
      title: "🎯 Competitive Path Optimizer",
      description: "Data-backed matrix modeling success metrics for GATE vs. CAT vs. Software Placements based on GPA and financial preferences.",
      glow: "border-orange-500/30 hover:border-orange-500/60 dark:hover:shadow-[0_0_20px_rgba(249,115,22,0.15)]",
    },
    {
      icon: Sparkles,
      title: "🛠️ SkillForge Timeline",
      description: "Automated, interactive weekly learning sprints custom-generated by Groq, directly linking free YouTube courses and projects.",
      glow: "border-amber-500/30 hover:border-amber-500/60 dark:hover:shadow-[0_0_20px_rgba(245,158,11,0.15)]",
    },
    {
      icon: FileSpreadsheet,
      title: "📨 ColdReach.ai Outreach",
      description: "Generates high-response LinkedIn connection request pitches and cold emails based on actual recruiter psychology in India.",
      glow: "border-indigo-500/30 hover:border-indigo-500/60 dark:hover:shadow-[0_0_20px_rgba(99,102,241,0.15)]",
    },
    {
      icon: Award,
      title: "💰 CTC breakdown & Negotiation Coach",
      description: "Parses complex Indian CTC packages, explaining Base, PF, Gratuity, ESOPs, and teaching you how to negotiate without losing offers.",
      glow: "border-cyan-500/30 hover:border-cyan-500/60 dark:hover:shadow-[0_0_20px_rgba(6,182,212,0.15)]",
    },
    {
      icon: ShieldAlert,
      title: "🛡️ ATS Ghost-Buster Analyzer",
      description: "Audits your resume layout for invisible extraction failures, multi-column parser leakage, and missing industry keywords.",
      glow: "border-rose-500/30 hover:border-rose-500/60 dark:hover:shadow-[0_0_20px_rgba(239,68,68,0.15)]",
    },
    {
      icon: Cpu,
      title: "🦄 IndieForge Side-Hustles",
      description: "Tailored micro-SaaS and freelance templates showing you how to capture Razorpay setups, build in public, and launch rapidly.",
      glow: "border-teal-500/30 hover:border-teal-500/60 dark:hover:shadow-[0_0_20px_rgba(20,184,166,0.15)]",
    },
  ]

  return (
    <div className="min-h-screen bg-slate-950 text-white selection:bg-purple-500/30 relative overflow-hidden">
      {/* Decorative Glows */}
      <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] gradient-glow-blue rounded-full pointer-events-none opacity-40"></div>
      <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] gradient-glow-purple rounded-full pointer-events-none opacity-40"></div>

      {/* Header */}
      <header className="border-b border-white/5 bg-zinc-950/70 backdrop-blur-md sticky top-0 z-50 transition-all">
        <div className="container mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center space-x-3">
            <div className="w-9 h-9 bg-gradient-to-tr from-blue-600 to-purple-600 rounded-xl flex items-center justify-center shadow-lg shadow-purple-500/20">
              <Sparkles className="w-5 h-5 text-white" />
            </div>
            <span className="text-2xl font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-white to-gray-400">CareerAI</span>
          </div>
          <div className="flex items-center space-x-4">
            <ThemeToggle />
            <Link href="/dashboard">
              <Button className="apple-btn-active bg-white text-zinc-950 hover:bg-white/90 rounded-full font-medium px-6">
                Enter Command Center
              </Button>
            </Link>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="py-24 px-6 text-center relative z-10 max-w-5xl mx-auto">
        <div className="inline-flex items-center space-x-2 bg-white/5 border border-white/10 rounded-full px-4 py-1.5 mb-6 backdrop-blur-sm animate-float">
          <Sparkles className="w-4 h-4 text-purple-400" />
          <span className="text-sm font-medium text-purple-300">The Apple UI of Career Guides</span>
        </div>
        
        <h1 className="text-5xl md:text-7xl font-bold tracking-tight mb-8 leading-[1.1]">
          Immersive Agentic Career <br />
          <span className="apple-gradient-text">Navigator for India</span>
        </h1>
        
        <p className="text-lg md:text-xl text-zinc-400 max-w-3xl mx-auto mb-10 leading-relaxed">
          Powered by ultra-fast Groq LLMs. Bypasses standard corporate filters, breaks out of Tier-3 campus boundaries, audits resumes for ATS, and maps high-impact upskilling sprints in real time.
        </p>

        <div className="flex flex-col sm:flex-row gap-5 justify-center">
          <Link href="/dashboard">
            <Button size="lg" className="apple-btn-active text-lg px-8 py-6 bg-gradient-to-r from-blue-600 to-purple-600 hover:from-blue-500 hover:to-purple-500 rounded-full border-0">
              Launch Agentic Engine
              <ArrowRight className="ml-2 w-5 h-5" />
            </Button>
          </Link>
          <Button variant="outline" size="lg" className="apple-btn-active text-lg px-8 py-6 rounded-full border-white/10 bg-white/5 hover:bg-white/10 text-white backdrop-blur-sm">
            Read Whitepaper
          </Button>
        </div>
      </section>

      {/* Innovative Features Grid */}
      <section className="py-24 px-6 relative z-10 border-t border-white/5 bg-zinc-900/30">
        <div className="container mx-auto max-w-6xl">
          <div className="text-center mb-20">
            <Badge variant="outline" className="border-purple-500/30 text-purple-400 px-3 py-1 mb-4 rounded-full">
              State-of-the-Art Features
            </Badge>
            <h2 className="text-3xl md:text-5xl font-bold text-white mb-6">Designed to Redefine Your Growth</h2>
            <p className="text-lg text-zinc-400 max-w-2xl mx-auto">
              We asked what top developers in India really needed to build high-end tech careers. Here is the response.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-2 gap-8">
            {innovativeFeatures.map((feature, index) => (
              <Card 
                key={index} 
                className={`bg-zinc-950/60 backdrop-blur-md border border-white/5 rounded-2xl transition-all duration-300 transform hover:scale-[1.01] overflow-hidden ${feature.glow}`}
              >
                <CardHeader className="flex flex-row items-center space-x-4 pb-4">
                  <div className="w-12 h-12 bg-white/5 rounded-xl flex items-center justify-center border border-white/10">
                    <feature.icon className="w-6 h-6 text-purple-400" />
                  </div>
                  <div>
                    <CardTitle className="text-xl text-white font-bold">{feature.title}</CardTitle>
                    <CardDescription className="text-purple-400/70 text-xs tracking-wider uppercase font-semibold">Innovative Feature #{index+1}</CardDescription>
                  </div>
                </CardHeader>
                <CardContent>
                  <p className="text-zinc-400 leading-relaxed">{feature.description}</p>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-28 px-6 text-center bg-gradient-to-b from-transparent to-zinc-950 relative border-t border-white/5">
        <div className="max-w-3xl mx-auto relative z-10">
          <h2 className="text-4xl font-bold mb-6">Ready to Break the Matrix?</h2>
          <p className="text-lg text-zinc-400 mb-10">
            Ditch outdated standard guidelines. Connect to the most interactive, speed-optimized career intelligence tool in India.
          </p>
          <Link href="/dashboard">
            <Button size="lg" className="apple-btn-active text-lg px-10 py-6 bg-white text-zinc-950 hover:bg-white/90 rounded-full font-bold">
              Access the Command Center Now
              <ArrowRight className="ml-2 w-5 h-5" />
            </Button>
          </Link>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-white/5 bg-zinc-950 py-12 px-6 text-center text-zinc-600 relative z-10">
        <div className="container mx-auto">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <Sparkles className="w-6 h-6 text-purple-500" />
            <span className="text-xl font-bold text-white tracking-tight">CareerAI</span>
          </div>
          <p className="text-sm">Empowering careers in India through elite Groq intelligence.</p>
          <p className="text-xs mt-4 text-zinc-700">© 2026 CareerAI. Crafted with meticulous Apple-inspired craftsmanship.</p>
        </div>
      </footer>
    </div>
  )
}
